### ISSUE TITLE
loadtest app fails to load cert from ca store

### ISSUE THREAD

**Issue by kasper573** [kasper573/mp#106]
```
TypeError: fetch failed
    at node:internal/deps/undici/undici:13484:13
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async <anonymous> (/home/kasper/code/mp/apps/loadtest/src/index.ts:33:25)
    at async Promise.allSettled (index 0)
    at async <anonymous> (/home/kasper/code/mp/apps/loadtest/src/index.ts:29:23)
    at async Promise.all (index 0)
    at async loadTestHTTP (/home/kasper/code/mp/apps/loadtest/src/index.ts:27:3)
    at async main (/home/kasper/code/mp/apps/loadtest/src/index.ts:18:3) {
  [cause]: Error: unable to get local issuer certificate
      at TLSSocket.onConnectSecure (node:_tls_wrap:1679:34)
      at TLSSocket.emit (node:events:524:28)
      at TLSSocket._finishInit (node:_tls_wrap:1078:8)
      at ssl.onhandshakedone (node:_tls_wrap:864:12) {
    code: 'UNABLE_TO_GET_ISSUER_CERT_LOCALLY'
  }
}
```

**Comment by kasper573** [comment]
solved by bypassing it in node
