### ISSUE TITLE
there seems to be a cache invalidation issue of js on new deploys

### ISSUE THREAD

**Issue by kasper573** [kasper573/mp#40]
runtime errors from what seems to be old js or something similar is my guess

```
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'camera')
    at kv.upsertCharacterActor (index-C4oEqHjz.js:104:3298)
    at index-C4oEqHjz.js:104:2226
    at ia.<anonymous> (index-C4oEqHjz.js:41:184962)
    at ia.c (index-C4oEqHjz.js:41:187520)
    at YE (index-C4oEqHjz.js:41:187888)
    at nt.subscribe (index-C4oEqHjz.js:41:184915)
    at kv.activate (index-C4oEqHjz.js:104:1532)
    at a.emit (index-C4oEqHjz.js:41:196298)
    at Fe.addChild (index-C4oEqHjz.js:46:44023)
    at index-C4oEqHjz.js:104:4184
```

```
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'input')
    at kv._onRender (index-C4oEqHjz.js:104:1741)
    at Y2.runOnRender (index-C4oEqHjz.js:46:41377)
    at we.render (SharedSystems-3I5jvuNn.js:309:9622)
    at PT.emit (index-C4oEqHjz.js:46:92146)
    at Pt.render (index-C4oEqHjz.js:46:94115)
    at fd.render (index-C4oEqHjz.js:46:98217)
    at fd.resize (webworkerAll-C6VXDxtF.js:1:1274)
    at fd.set (webworkerAll-C6VXDxtF.js:1:760)
    at fd.init (webworkerAll-C6VXDxtF.js:1:1337)
    at index-C4oEqHjz.js:46:98179
```

**Comment by kasper573** [comment]
Fixed in https://github.com/kasper573/mp/commit/d18653de7ee6522393662c460f401dd60334ece3
